// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://johltsnnsoxulzhynwvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaGx0c25uc294dWx6aHlud3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzcwNDcsImV4cCI6MjA3MjIxMzA0N30.HmWN2fYWChC7KGSZGRXEnTM6j-lpFZANC5WhFiKOohg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});